### ISSUE TITLE
Should we rename the tool to something different than "aversion"?

### ISSUE THREAD

**Issue by draganjovanovic1** [mocosha/assembly-version#1]
Maybe aversion is not the right name: https://dictionary.cambridge.org/dictionary/english/aversion

**Comment by draganjovanovic1** [comment]
Maybe "aver"? It is short and therefore easy to type and remember.

**Comment by bramom** [comment]
"aver" is fine with me, @bpantovic @milos92100

**Comment by bpantovic** [comment]
"aversion" renamed to "aver"
