### ISSUE TITLE
Setup CI for master branch?

### ISSUE THREAD

**Issue by draganjovanovic1** [mocosha/assembly-version#7]
Use https://travis-ci.org and add badge in readme.md.

**Comment by milos92100** [comment]
I would try to solve this. Is it @draganjovanovic1  is it decided to evaluate travis-ci.org ?
If, yes we should probably create a mocoha account for Travis, or maybe there is already an account for that created?

**Comment by draganjovanovic1** [comment]
I have activated build for the repo in Travis-CI. You may proceed with creating build scripts and yml.

**Comment by draganjovanovic1** [comment]
@milos92100, thanks for the [PR](https://github.com/mocosha/assembly-version/pull/15). Could you please add Travis-CI build status badge on top of to the readme file as well?

Like this:
[![Build Status](https://api.travis-ci.org/mocosha/assembly-version.svg?branch=master)](https://travis-ci.org/mocosha/assembly-version)

**Comment by milos92100** [comment]
No problem, sure will do that. Kiss.

**Comment by draganjovanovic1** [comment]
Merged. Thanks.
